name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger the pipeline manually'
        required: true
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test and compile Kubeflow pipeline
        run: |
          python test_pipeline.py

      - name: Build Docker image
        run: |
          docker build -t my-ml-app:latest .

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-ml-app:latest my-dockerhub-username/my-ml-app:latest
          docker push my-dockerhub-username/my-ml-app:latest

      - name: Upload Kubeflow pipeline
        env:
          KFP_HOST: ${{ secrets.KFP_HOST }}
          KFP_NAMESPACE: ${{ secrets.KFP_NAMESPACE }}
          KFP_USERNAME: ${{ secrets.KFP_USERNAME }}
          KFP_PASSWORD: ${{ secrets.KFP_PASSWORD }}
        run: |
          pip install kfp
          export KFP_HOST=${{ secrets.KFP_HOST }}
          export KFP_NAMESPACE=${{ secrets.KFP_NAMESPACE }}
          export KFP_USERNAME=${{ secrets.KFP_USERNAME }}
          export KFP_PASSWORD=${{ secrets.KFP_PASSWORD }}
          kfp run pipeline ml_pipeline.yaml
